### ISSUE TITLE
Remove /core prefix

### ISSUE THREAD

**Issue by iurisilvio** [freedomsponsors/www.freedomsponsors.org#128]
It is a big thing to change, but I really does not like all urls have a /core prefix. Also it is a bad smell, probably this core app should be splited in some other apps.

**Comment by Enygma2002** [comment]
Well, this change broke the jira plugin, which was not updated to support the new URL format.

**Comment by tonylampada** [comment]
Opened #349. Will work on it ASAP.
Thanks!
