### ISSUE TITLE
Can this be adapted and used to crowdfund persons (donation for personal projects) ?

### ISSUE THREAD

**Issue by HTCode** [freedomsponsors/www.freedomsponsors.org#345]
I am wondering if it is easily possible to modify freedomsponsors and use it as a donation crowdfunding platform ? Is is complicated ? Is that even allowed ?

**Comment by tonylampada** [comment]
It's allowed but in practice it would be too much of hassle to implement all the changes necessary to make it happen.

You are probably better off using something designed specifically for that end like http://www.selfstarter.us
