### ISSUE TITLE
Investigate problem with JIRA plugin integration

### ISSUE THREAD

**Issue by tonylampada** [freedomsponsors/www.freedomsponsors.org#349]
https://github.com/freedomsponsors/www.freedomsponsors.org/commit/53ae7a4019fbac5974e06335ae88611ed3b93c0d#commitcomment-24459613

**Comment by Enygma2002** [comment]
It should be simple, just to update the link at https://github.com/freedomsponsors/freedomsponsors-jira-plugin/blob/master/src/main/resources/atlassian-plugin.xml#L13 and do a quick release.

**Comment by tonylampada** [comment]
:+1:

**Comment by Enygma2002** [comment]
https://github.com/freedomsponsors/freedomsponsors-jira-plugin/pull/7/files could help :)

**Comment by Enygma2002** [comment]
For more context, going to https://jira.xwiki.org/browse/XWIKI-4638 you get the link https://freedomsponsors.org/core/issue/sponsor?trackerURL=https://jira.xwiki.org/browse/XWIKI-4638 which leads to a 404 error.

We're running version 1.1 of the jira plugin on a Jira v6.1.9 instance (jira.xwiki.org).

**Comment by tonylampada** [comment]
I fixed this on freedomsponsors side. The URL `https://freedomsponsors.org/core/issue/sponsor?trackerURL=https://jira.xwiki.org/browse/XWIKI-4638` now returns a redirect to `https://freedomsponsors.org/issue/sponsor?trackerURL=https://jira.xwiki.org/browse/XWIKI-4638`

This way doesn't force everyone to update their JIRA (or even other issue trackers) plugins.

**Comment by Enygma2002** [comment]
Cool! Thanks!
